### ISSUE TITLE
Allow JSDOM fragments

### ISSUE THREAD

**Issue by chanceaclark** [sparanoid/grunt-assets-inline#30]
I have a repository that takes HTML partials and maps them out into dist/. I don't necessarily need the whole DOM structure for each partial file but I would still like to inline compiled SCSS files into partials.

Since JSDOM wraps the html string in `<html>`, `<head>`, and `<body>` tags on input, I'd like to suggest adding a flag to the options object return an unserialized version.

**Comment by chanceaclark** [comment]
I created a PR #31 for this, and it is a bit messy/hacky/wonky, but something of this work-a-round is what I'm looking for.

**Comment by sparanoid** [comment]
Done, thanks!
