### ISSUE TITLE
Favicons are not inlined?

### ISSUE THREAD

**Issue by dennisguse** [sparanoid/grunt-assets-inline#41]
assets-inline works as expected except that favicons are not inline.
I am using v1.2.1 from npm.

The code that should be inlined:
```
        <link rel="icon" type="image/svg+xml" href="img/TheKarte-logo.svg">
        <link rel="icon" type="image/png" href="img/TheKarte-logo.png" sizes="96x96">
```
The project I having this issue with: [TheKarte](https://github.com/dennisguse/TheKarte)
Execute `grunt dist` and check `dist/TheKarte.html` for favicons.

**Comment by sparanoid** [comment]
`inlineLinkTags` is disabled [by default](https://github.com/sparanoid/grunt-assets-inline#inlinelinktags).
