### ISSUE TITLE
Comment in fragment breaks with "Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by printminion** [sparanoid/grunt-assets-inline#49]
Error: "Cannot read property 'replace' of undefined" is given if first element of html template is Node.COMMENT_NODE

To reproduce:
 * use option "serialize: false"
 * HTML Template file must contain comment node e.g.  as a first node
`
<img src="svg/disable-wysiwyg.svg">`

I created a PR #48 for this

**Comment by sparanoid** [comment]
Fixed via https://github.com/sparanoid/grunt-assets-inline/pull/48
